const $=s=>document.querySelector(s), canvas=$('#canvas'), stage=$('#stage');let notes=[],zoom=1,pan={x:0,y:0},drag=null, selected=new Set(), saveTimer;
const colors=['#292d38','#303b55','#3c334d','#3b493a','#51412e','#51343c'];
function fa(n){return n.toLocaleString('fa-IR')} function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>chrome.storage.local.set({notes}),150)}
function render(){canvas.innerHTML='';notes.forEach(n=>{let el=document.createElement('article');el.className='note'+(selected.has(n.id)?' selected':'');el.dataset.id=n.id;el.style.cssText=`left:${n.x}px;top:${n.y}px;--note:${n.color}`;el.innerHTML=`<div class="note-head"><input value="${esc(n.title||'یادداشت جدید')}" aria-label="عنوان"><div class="note-actions"><button class="copy" title="کپی">⧉</button><button class="color" title="رنگ">●</button><button class="del" title="حذف">×</button></div></div><div class="note-body" contenteditable="true">${esc(n.text||'')}</div>`;canvas.append(el)});canvas.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('#count').textContent=fa(notes.length)+' یادداشت';$('#zoom').textContent=fa(Math.round(zoom*100))+'٪';$('.empty').classList.toggle('hide',notes.length>0)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function add(text='',x=120-pan.x,y=100-pan.y){let n={id:crypto.randomUUID(),title:'یادداشت جدید',text,x,y,color:colors[0]};notes.push(n);selected.clear();selected.add(n.id);persist();render();setTimeout(()=>document.querySelector(`[data-id="${n.id}"] .note-body`).focus(),30)}
$('#new').onclick=()=>add();$('#theme').onclick=()=>{document.body.classList.toggle('light');chrome.storage.local.set({light:document.body.classList.contains('light')})};$('#copySelected').onclick=async()=>{let a=notes.filter(n=>selected.has(n.id));if(!a.length)return;for(let n of a){try{await navigator.clipboard.writeText(`${n.title}\n${n.text}`)}catch(e){}};localStorage.setItem('note-clipboard-slots',JSON.stringify(a.map(n=>({title:n.title,text:n.text})))) ; alert(`${fa(a.length)} یادداشت در کلیپ‌بوردهای داخلی ذخیره شد.`)};
stage.addEventListener('wheel',e=>{e.preventDefault();let old=zoom;zoom=Math.max(.35,Math.min(2.5,zoom*(e.deltaY<0?1.1:.9)));let r=stage.getBoundingClientRect();pan.x=(pan.x-(e.clientX-r.left))*(zoom/old)+(e.clientX-r.left);pan.y=(pan.y-(e.clientY-r.top))*(zoom/old)+(e.clientY-r.top);render()},{passive:false});
stage.oncontextmenu=e=>{if(e.target===stage||e.target===canvas){e.preventDefault();let m=document.createElement('div');m.className='context';m.style.left=e.clientX+'px';m.style.top=e.clientY+'px';m.innerHTML='<button>＋ یادداشت جدید</button><button>کپی یادداشت‌های انتخاب‌شده</button>';document.body.append(m);m.children[0].onclick=()=>{add((window.getSelection()||'').toString(),(e.clientX-stage.offsetLeft-pan.x)/zoom,(e.clientY-stage.offsetTop-pan.y)/zoom);m.remove()};m.children[1].onclick=()=>{$('#copySelected').click();m.remove()};setTimeout(()=>document.addEventListener('click',()=>m.remove(),{once:true}),0)}};
stage.onmousedown=e=>{if(e.button===2){drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};stage.style.cursor='grabbing'}else if(e.target===stage||e.target===canvas){let box={x:e.clientX,y:e.clientY};let move=ev=>{if(Math.hypot(ev.clientX-box.x,ev.clientY-box.y)>5) document.body.classList.add('selecting')};let up=ev=>{document.body.classList.remove('selecting');let x1=Math.min(box.x,ev.clientX),x2=Math.max(box.x,ev.clientX),y1=Math.min(box.y,ev.clientY),y2=Math.max(box.y,ev.clientY);document.querySelectorAll('.note').forEach(el=>{let r=el.getBoundingClientRect();if(r.left<x2&&r.right>x1&&r.top<y2&&r.bottom>y1)selected.add(el.dataset.id)});render();stage.removeEventListener('mousemove',move);stage.removeEventListener('mouseup',up)};stage.addEventListener('mousemove',move);stage.addEventListener('mouseup',up)}};window.onmousemove=e=>{if(drag){pan.x=drag.px+e.clientX-drag.x;pan.y=drag.py+e.clientY-drag.y;render()}};window.onmouseup=()=>{if(drag){drag=null;stage.style.cursor='grab';persist()}};
canvas.onclick=e=>{let el=e.target.closest('.note');if(!el)return;if(!e.ctrlKey&&!e.metaKey)selected.clear();selected.add(el.dataset.id);render()};canvas.onmousedown=e=>{let el=e.target.closest('.note');if(!el||e.button!==0||e.target.closest('input,.note-body,.note-actions'))return;let n=notes.find(x=>x.id===el.dataset.id),sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;let mv=ev=>{n.x=ox+(ev.clientX-sx)/zoom;n.y=oy+(ev.clientY-sy)/zoom;el.style.left=n.x+'px';el.style.top=n.y+'px'};let up=()=>{persist();window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up)};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up)};
canvas.oninput=e=>{let el=e.target.closest('.note'),n=notes.find(x=>x.id===el.dataset.id);if(e.target.matches('input'))n.title=e.target.value;else n.text=e.target.innerText;persist()};canvas.onclick=e=>{let el=e.target.closest('.note');if(!el)return;let n=notes.find(x=>x.id===el.dataset.id);if(e.target.closest('.del')){notes=notes.filter(x=>x!==n);selected.delete(n.id);persist();render()}else if(e.target.closest('.copy'))navigator.clipboard.writeText(`${n.title}\n${n.text}`);else if(e.target.closest('.color')){let p=document.createElement('div');p.className='palette';colors.forEach(c=>{let b=document.createElement('i');b.className='sw';b.style.background=c;b.onclick=()=>{n.color=c;p.remove();persist();render()};p.append(b)});el.append(p)}else if(!e.target.closest('input,.note-body')){if(!e.ctrlKey&&!e.metaKey)selected.clear();selected.add(n.id);render()}};
chrome.storage.local.get(['notes','light','pendingNote']).then(d=>{notes=d.notes||[];if(d.light)document.body.classList.add('light');if(d.pendingNote){add(d.pendingNote.text);chrome.storage.local.remove('pendingNote')}else render()});
